/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.analysis;

import lyrics.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseACancion(ACancion node);
    void caseAMetadatoLinea(AMetadatoLinea node);
    void caseATiempoLinea(ATiempoLinea node);
    void caseATxtElemento(ATxtElemento node);
    void caseANumElemento(ANumElemento node);
    void caseADpElemento(ADpElemento node);
    void caseAPpElemento(APpElemento node);

    void caseTCorcheteIzq(TCorcheteIzq node);
    void caseTCorcheteDer(TCorcheteDer node);
    void caseTDosPuntos(TDosPuntos node);
    void caseTPPunto(TPPunto node);
    void caseTNumero(TNumero node);
    void caseTTexto(TTexto node);
    void caseTBlanco(TBlanco node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
