/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.analysis;

import java.util.*;
import lyrics.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACancion(ACancion node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMetadatoLinea(AMetadatoLinea node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATiempoLinea(ATiempoLinea node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATxtElemento(ATxtElemento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumElemento(ANumElemento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADpElemento(ADpElemento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPpElemento(APpElemento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCorcheteIzq(TCorcheteIzq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCorcheteDer(TCorcheteDer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDosPuntos(TDosPuntos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPPunto(TPPunto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumero(TNumero node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTexto(TTexto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlanco(TBlanco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
