/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.analysis;

import java.util.*;
import lyrics.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPCancion().apply(this);
        outStart(node);
    }

    public void inACancion(ACancion node)
    {
        defaultIn(node);
    }

    public void outACancion(ACancion node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACancion(ACancion node)
    {
        inACancion(node);
        {
            List<PLinea> copy = new ArrayList<PLinea>(node.getLinea());
            Collections.reverse(copy);
            for(PLinea e : copy)
            {
                e.apply(this);
            }
        }
        outACancion(node);
    }

    public void inAMetadatoLinea(AMetadatoLinea node)
    {
        defaultIn(node);
    }

    public void outAMetadatoLinea(AMetadatoLinea node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMetadatoLinea(AMetadatoLinea node)
    {
        inAMetadatoLinea(node);
        if(node.getCorcheteDer() != null)
        {
            node.getCorcheteDer().apply(this);
        }
        {
            List<PElemento> copy = new ArrayList<PElemento>(node.getVal());
            Collections.reverse(copy);
            for(PElemento e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getDosPuntos() != null)
        {
            node.getDosPuntos().apply(this);
        }
        if(node.getEtiq() != null)
        {
            node.getEtiq().apply(this);
        }
        if(node.getCorcheteIzq() != null)
        {
            node.getCorcheteIzq().apply(this);
        }
        outAMetadatoLinea(node);
    }

    public void inATiempoLinea(ATiempoLinea node)
    {
        defaultIn(node);
    }

    public void outATiempoLinea(ATiempoLinea node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATiempoLinea(ATiempoLinea node)
    {
        inATiempoLinea(node);
        {
            List<PElemento> copy = new ArrayList<PElemento>(node.getLetra());
            Collections.reverse(copy);
            for(PElemento e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getCorcheteDer() != null)
        {
            node.getCorcheteDer().apply(this);
        }
        if(node.getC() != null)
        {
            node.getC().apply(this);
        }
        if(node.getPPunto() != null)
        {
            node.getPPunto().apply(this);
        }
        if(node.getS() != null)
        {
            node.getS().apply(this);
        }
        if(node.getDosPuntos() != null)
        {
            node.getDosPuntos().apply(this);
        }
        if(node.getM() != null)
        {
            node.getM().apply(this);
        }
        if(node.getCorcheteIzq() != null)
        {
            node.getCorcheteIzq().apply(this);
        }
        outATiempoLinea(node);
    }

    public void inATxtElemento(ATxtElemento node)
    {
        defaultIn(node);
    }

    public void outATxtElemento(ATxtElemento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATxtElemento(ATxtElemento node)
    {
        inATxtElemento(node);
        if(node.getTexto() != null)
        {
            node.getTexto().apply(this);
        }
        outATxtElemento(node);
    }

    public void inANumElemento(ANumElemento node)
    {
        defaultIn(node);
    }

    public void outANumElemento(ANumElemento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumElemento(ANumElemento node)
    {
        inANumElemento(node);
        if(node.getNumero() != null)
        {
            node.getNumero().apply(this);
        }
        outANumElemento(node);
    }

    public void inADpElemento(ADpElemento node)
    {
        defaultIn(node);
    }

    public void outADpElemento(ADpElemento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADpElemento(ADpElemento node)
    {
        inADpElemento(node);
        if(node.getDosPuntos() != null)
        {
            node.getDosPuntos().apply(this);
        }
        outADpElemento(node);
    }

    public void inAPpElemento(APpElemento node)
    {
        defaultIn(node);
    }

    public void outAPpElemento(APpElemento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPpElemento(APpElemento node)
    {
        inAPpElemento(node);
        if(node.getPPunto() != null)
        {
            node.getPPunto().apply(this);
        }
        outAPpElemento(node);
    }
}
