/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.parser;

import lyrics.lexer.*;
import lyrics.node.*;
import lyrics.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PCancion node1 = (PCancion) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce ACancion */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AAtiempolinea1Linea */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list, false);
            }
            break;
            case 2: /* reduce AAtiempolinea2Linea */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce ATxtElemento */
            {
                ArrayList<Object> list = new3();
                push(goTo(2), list, false);
            }
            break;
            case 4: /* reduce ANumElemento */
            {
                ArrayList<Object> list = new4();
                push(goTo(2), list, false);
            }
            break;
            case 5: /* reduce ADpElemento */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list, false);
            }
            break;
            case 6: /* reduce APpElemento */
            {
                ArrayList<Object> list = new6();
                push(goTo(2), list, false);
            }
            break;
            case 7: /* reduce ATerminal$Linea */
            {
                ArrayList<Object> list = new7();
                push(goTo(3), list, true);
            }
            break;
            case 8: /* reduce ANonTerminal$Linea */
            {
                ArrayList<Object> list = new8();
                push(goTo(3), list, true);
            }
            break;
            case 9: /* reduce ATerminal$Elemento */
            {
                ArrayList<Object> list = new9();
                push(goTo(4), list, true);
            }
            break;
            case 10: /* reduce ANonTerminal$Elemento */
            {
                ArrayList<Object> list = new10();
                push(goTo(4), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce ACancion */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCancion pcancionNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pcancionNode1 = new ACancion(listNode3);
        }
	nodeList.add(pcancionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AAtiempolinea1Linea */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLinea plineaNode1;
        {
            // Block
        TCorcheteIzq tcorcheteizqNode2;
        TNumero tnumeroNode3;
        TDosPuntos tdospuntosNode4;
        TNumero tnumeroNode5;
        TPPunto tppuntoNode6;
        TNumero tnumeroNode7;
        TCorcheteDer tcorchetederNode8;
        LinkedList<Object> listNode9 = new LinkedList<Object>();
        tcorcheteizqNode2 = (TCorcheteIzq)nodeArrayList1.get(0);
        tnumeroNode3 = (TNumero)nodeArrayList2.get(0);
        tdospuntosNode4 = (TDosPuntos)nodeArrayList3.get(0);
        tnumeroNode5 = (TNumero)nodeArrayList4.get(0);
        tppuntoNode6 = (TPPunto)nodeArrayList5.get(0);
        tnumeroNode7 = (TNumero)nodeArrayList6.get(0);
        tcorchetederNode8 = (TCorcheteDer)nodeArrayList7.get(0);
        {
            // Block
        }

        plineaNode1 = new ATiempoLinea(tcorcheteizqNode2, tnumeroNode3, tdospuntosNode4, tnumeroNode5, tppuntoNode6, tnumeroNode7, tcorchetederNode8, listNode9);
        }
	nodeList.add(plineaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AAtiempolinea2Linea */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLinea plineaNode1;
        {
            // Block
        TCorcheteIzq tcorcheteizqNode2;
        TNumero tnumeroNode3;
        TDosPuntos tdospuntosNode4;
        TNumero tnumeroNode5;
        TPPunto tppuntoNode6;
        TNumero tnumeroNode7;
        TCorcheteDer tcorchetederNode8;
        LinkedList<Object> listNode10 = new LinkedList<Object>();
        tcorcheteizqNode2 = (TCorcheteIzq)nodeArrayList1.get(0);
        tnumeroNode3 = (TNumero)nodeArrayList2.get(0);
        tdospuntosNode4 = (TDosPuntos)nodeArrayList3.get(0);
        tnumeroNode5 = (TNumero)nodeArrayList4.get(0);
        tppuntoNode6 = (TPPunto)nodeArrayList5.get(0);
        tnumeroNode7 = (TNumero)nodeArrayList6.get(0);
        tcorchetederNode8 = (TCorcheteDer)nodeArrayList7.get(0);
        {
            // Block
        LinkedList<Object> listNode9 = new LinkedList<Object>();
        listNode9 = (LinkedList)nodeArrayList8.get(0);
	if(listNode9 != null)
	{
	  listNode10.addAll(listNode9);
	}
        }

        plineaNode1 = new ATiempoLinea(tcorcheteizqNode2, tnumeroNode3, tdospuntosNode4, tnumeroNode5, tppuntoNode6, tnumeroNode7, tcorchetederNode8, listNode10);
        }
	nodeList.add(plineaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce ATxtElemento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElemento pelementoNode1;
        {
            // Block
        TTexto ttextoNode2;
        ttextoNode2 = (TTexto)nodeArrayList1.get(0);

        pelementoNode1 = new ATxtElemento(ttextoNode2);
        }
	nodeList.add(pelementoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce ANumElemento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElemento pelementoNode1;
        {
            // Block
        TNumero tnumeroNode2;
        tnumeroNode2 = (TNumero)nodeArrayList1.get(0);

        pelementoNode1 = new ANumElemento(tnumeroNode2);
        }
	nodeList.add(pelementoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ADpElemento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElemento pelementoNode1;
        {
            // Block
        TDosPuntos tdospuntosNode2;
        tdospuntosNode2 = (TDosPuntos)nodeArrayList1.get(0);

        pelementoNode1 = new ADpElemento(tdospuntosNode2);
        }
	nodeList.add(pelementoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce APpElemento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElemento pelementoNode1;
        {
            // Block
        TPPunto tppuntoNode2;
        tppuntoNode2 = (TPPunto)nodeArrayList1.get(0);

        pelementoNode1 = new APpElemento(tppuntoNode2);
        }
	nodeList.add(pelementoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce ATerminal$Linea */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PLinea plineaNode1;
        plineaNode1 = (PLinea)nodeArrayList1.get(0);
	if(plineaNode1 != null)
	{
	  listNode2.add(plineaNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce ANonTerminal$Linea */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PLinea plineaNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        plineaNode2 = (PLinea)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(plineaNode2 != null)
	{
	  listNode3.add(plineaNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce ATerminal$Elemento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PElemento pelementoNode1;
        pelementoNode1 = (PElemento)nodeArrayList1.get(0);
	if(pelementoNode1 != null)
	{
	  listNode2.add(pelementoNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ANonTerminal$Elemento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PElemento pelementoNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pelementoNode2 = (PElemento)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pelementoNode2 != null)
	{
	  listNode3.add(pelementoNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, },
			{{-1, ERROR, 1}, {4, SHIFT, 5}, },
			{{-1, ERROR, 2}, {6, ACCEPT, -1}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, },
			{{-1, ERROR, 5}, {2, SHIFT, 7}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 7}, {4, SHIFT, 8}, },
			{{-1, ERROR, 8}, {3, SHIFT, 9}, },
			{{-1, ERROR, 9}, {4, SHIFT, 10}, },
			{{-1, ERROR, 10}, {1, SHIFT, 11}, },
			{{-1, REDUCE, 1}, {2, SHIFT, 12}, {3, SHIFT, 13}, {4, SHIFT, 14}, {5, SHIFT, 15}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 2}, {2, SHIFT, 12}, {3, SHIFT, 13}, {4, SHIFT, 14}, {5, SHIFT, 15}, },
			{{-1, REDUCE, 10}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, {4, 6}, },
			{{-1, 16}, {17, 18}, },
			{{-1, 4}, },
			{{-1, 17}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: '['",
			"expecting: numero",
			"expecting: EOF",
			"expecting: '[', EOF",
			"expecting: ':'",
			"expecting: '.'",
			"expecting: ']'",
			"expecting: '[', ':', '.', numero, texto, EOF",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 4, 3, 1, 5, 1, 6, 7, 7, 7, 7, 7, 7, 7, 7, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
