/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.parser;

import lyrics.node.*;
import lyrics.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTCorcheteIzq(@SuppressWarnings("unused") TCorcheteIzq node)
    {
        this.index = 0;
    }

    @Override
    public void caseTCorcheteDer(@SuppressWarnings("unused") TCorcheteDer node)
    {
        this.index = 1;
    }

    @Override
    public void caseTDosPuntos(@SuppressWarnings("unused") TDosPuntos node)
    {
        this.index = 2;
    }

    @Override
    public void caseTPPunto(@SuppressWarnings("unused") TPPunto node)
    {
        this.index = 3;
    }

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 4;
    }

    @Override
    public void caseTTexto(@SuppressWarnings("unused") TTexto node)
    {
        this.index = 5;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 6;
    }
}
