/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.node;

import java.util.*;
import lyrics.analysis.*;

@SuppressWarnings("nls")
public final class ACancion extends PCancion
{
    private final LinkedList<PLinea> _linea_ = new LinkedList<PLinea>();

    public ACancion()
    {
        // Constructor
    }

    public ACancion(
        @SuppressWarnings("hiding") List<?> _linea_)
    {
        // Constructor
        setLinea(_linea_);

    }

    @Override
    public Object clone()
    {
        return new ACancion(
            cloneList(this._linea_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACancion(this);
    }

    public LinkedList<PLinea> getLinea()
    {
        return this._linea_;
    }

    public void setLinea(List<?> list)
    {
        for(PLinea e : this._linea_)
        {
            e.parent(null);
        }
        this._linea_.clear();

        for(Object obj_e : list)
        {
            PLinea e = (PLinea) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._linea_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._linea_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._linea_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PLinea> i = this._linea_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PLinea) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
