/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.node;

import lyrics.analysis.*;

@SuppressWarnings("nls")
public final class ADpElemento extends PElemento
{
    private TDosPuntos _dosPuntos_;

    public ADpElemento()
    {
        // Constructor
    }

    public ADpElemento(
        @SuppressWarnings("hiding") TDosPuntos _dosPuntos_)
    {
        // Constructor
        setDosPuntos(_dosPuntos_);

    }

    @Override
    public Object clone()
    {
        return new ADpElemento(
            cloneNode(this._dosPuntos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADpElemento(this);
    }

    public TDosPuntos getDosPuntos()
    {
        return this._dosPuntos_;
    }

    public void setDosPuntos(TDosPuntos node)
    {
        if(this._dosPuntos_ != null)
        {
            this._dosPuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dosPuntos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dosPuntos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dosPuntos_ == child)
        {
            this._dosPuntos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dosPuntos_ == oldChild)
        {
            setDosPuntos((TDosPuntos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
