/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.node;

import java.util.*;
import lyrics.analysis.*;

@SuppressWarnings("nls")
public final class AMetadatoLinea extends PLinea
{
    private TCorcheteIzq _corcheteIzq_;
    private TTexto _etiq_;
    private TDosPuntos _dosPuntos_;
    private final LinkedList<PElemento> _val_ = new LinkedList<PElemento>();
    private TCorcheteDer _corcheteDer_;

    public AMetadatoLinea()
    {
        // Constructor
    }

    public AMetadatoLinea(
        @SuppressWarnings("hiding") TCorcheteIzq _corcheteIzq_,
        @SuppressWarnings("hiding") TTexto _etiq_,
        @SuppressWarnings("hiding") TDosPuntos _dosPuntos_,
        @SuppressWarnings("hiding") List<?> _val_,
        @SuppressWarnings("hiding") TCorcheteDer _corcheteDer_)
    {
        // Constructor
        setCorcheteIzq(_corcheteIzq_);

        setEtiq(_etiq_);

        setDosPuntos(_dosPuntos_);

        setVal(_val_);

        setCorcheteDer(_corcheteDer_);

    }

    @Override
    public Object clone()
    {
        return new AMetadatoLinea(
            cloneNode(this._corcheteIzq_),
            cloneNode(this._etiq_),
            cloneNode(this._dosPuntos_),
            cloneList(this._val_),
            cloneNode(this._corcheteDer_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMetadatoLinea(this);
    }

    public TCorcheteIzq getCorcheteIzq()
    {
        return this._corcheteIzq_;
    }

    public void setCorcheteIzq(TCorcheteIzq node)
    {
        if(this._corcheteIzq_ != null)
        {
            this._corcheteIzq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corcheteIzq_ = node;
    }

    public TTexto getEtiq()
    {
        return this._etiq_;
    }

    public void setEtiq(TTexto node)
    {
        if(this._etiq_ != null)
        {
            this._etiq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._etiq_ = node;
    }

    public TDosPuntos getDosPuntos()
    {
        return this._dosPuntos_;
    }

    public void setDosPuntos(TDosPuntos node)
    {
        if(this._dosPuntos_ != null)
        {
            this._dosPuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dosPuntos_ = node;
    }

    public LinkedList<PElemento> getVal()
    {
        return this._val_;
    }

    public void setVal(List<?> list)
    {
        for(PElemento e : this._val_)
        {
            e.parent(null);
        }
        this._val_.clear();

        for(Object obj_e : list)
        {
            PElemento e = (PElemento) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._val_.add(e);
        }
    }

    public TCorcheteDer getCorcheteDer()
    {
        return this._corcheteDer_;
    }

    public void setCorcheteDer(TCorcheteDer node)
    {
        if(this._corcheteDer_ != null)
        {
            this._corcheteDer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corcheteDer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._corcheteIzq_)
            + toString(this._etiq_)
            + toString(this._dosPuntos_)
            + toString(this._val_)
            + toString(this._corcheteDer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._corcheteIzq_ == child)
        {
            this._corcheteIzq_ = null;
            return;
        }

        if(this._etiq_ == child)
        {
            this._etiq_ = null;
            return;
        }

        if(this._dosPuntos_ == child)
        {
            this._dosPuntos_ = null;
            return;
        }

        if(this._val_.remove(child))
        {
            return;
        }

        if(this._corcheteDer_ == child)
        {
            this._corcheteDer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._corcheteIzq_ == oldChild)
        {
            setCorcheteIzq((TCorcheteIzq) newChild);
            return;
        }

        if(this._etiq_ == oldChild)
        {
            setEtiq((TTexto) newChild);
            return;
        }

        if(this._dosPuntos_ == oldChild)
        {
            setDosPuntos((TDosPuntos) newChild);
            return;
        }

        for(ListIterator<PElemento> i = this._val_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PElemento) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._corcheteDer_ == oldChild)
        {
            setCorcheteDer((TCorcheteDer) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
