/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.node;

import lyrics.analysis.*;

@SuppressWarnings("nls")
public final class APpElemento extends PElemento
{
    private TPPunto _pPunto_;

    public APpElemento()
    {
        // Constructor
    }

    public APpElemento(
        @SuppressWarnings("hiding") TPPunto _pPunto_)
    {
        // Constructor
        setPPunto(_pPunto_);

    }

    @Override
    public Object clone()
    {
        return new APpElemento(
            cloneNode(this._pPunto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPpElemento(this);
    }

    public TPPunto getPPunto()
    {
        return this._pPunto_;
    }

    public void setPPunto(TPPunto node)
    {
        if(this._pPunto_ != null)
        {
            this._pPunto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pPunto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pPunto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pPunto_ == child)
        {
            this._pPunto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pPunto_ == oldChild)
        {
            setPPunto((TPPunto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
