/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.node;

import java.util.*;
import lyrics.analysis.*;

@SuppressWarnings("nls")
public final class ATiempoLinea extends PLinea
{
    private TCorcheteIzq _corcheteIzq_;
    private TNumero _m_;
    private TDosPuntos _dosPuntos_;
    private TNumero _s_;
    private TPPunto _pPunto_;
    private TNumero _c_;
    private TCorcheteDer _corcheteDer_;
    private final LinkedList<PElemento> _letra_ = new LinkedList<PElemento>();

    public ATiempoLinea()
    {
        // Constructor
    }

    public ATiempoLinea(
        @SuppressWarnings("hiding") TCorcheteIzq _corcheteIzq_,
        @SuppressWarnings("hiding") TNumero _m_,
        @SuppressWarnings("hiding") TDosPuntos _dosPuntos_,
        @SuppressWarnings("hiding") TNumero _s_,
        @SuppressWarnings("hiding") TPPunto _pPunto_,
        @SuppressWarnings("hiding") TNumero _c_,
        @SuppressWarnings("hiding") TCorcheteDer _corcheteDer_,
        @SuppressWarnings("hiding") List<?> _letra_)
    {
        // Constructor
        setCorcheteIzq(_corcheteIzq_);

        setM(_m_);

        setDosPuntos(_dosPuntos_);

        setS(_s_);

        setPPunto(_pPunto_);

        setC(_c_);

        setCorcheteDer(_corcheteDer_);

        setLetra(_letra_);

    }

    @Override
    public Object clone()
    {
        return new ATiempoLinea(
            cloneNode(this._corcheteIzq_),
            cloneNode(this._m_),
            cloneNode(this._dosPuntos_),
            cloneNode(this._s_),
            cloneNode(this._pPunto_),
            cloneNode(this._c_),
            cloneNode(this._corcheteDer_),
            cloneList(this._letra_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATiempoLinea(this);
    }

    public TCorcheteIzq getCorcheteIzq()
    {
        return this._corcheteIzq_;
    }

    public void setCorcheteIzq(TCorcheteIzq node)
    {
        if(this._corcheteIzq_ != null)
        {
            this._corcheteIzq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corcheteIzq_ = node;
    }

    public TNumero getM()
    {
        return this._m_;
    }

    public void setM(TNumero node)
    {
        if(this._m_ != null)
        {
            this._m_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._m_ = node;
    }

    public TDosPuntos getDosPuntos()
    {
        return this._dosPuntos_;
    }

    public void setDosPuntos(TDosPuntos node)
    {
        if(this._dosPuntos_ != null)
        {
            this._dosPuntos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dosPuntos_ = node;
    }

    public TNumero getS()
    {
        return this._s_;
    }

    public void setS(TNumero node)
    {
        if(this._s_ != null)
        {
            this._s_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._s_ = node;
    }

    public TPPunto getPPunto()
    {
        return this._pPunto_;
    }

    public void setPPunto(TPPunto node)
    {
        if(this._pPunto_ != null)
        {
            this._pPunto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pPunto_ = node;
    }

    public TNumero getC()
    {
        return this._c_;
    }

    public void setC(TNumero node)
    {
        if(this._c_ != null)
        {
            this._c_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._c_ = node;
    }

    public TCorcheteDer getCorcheteDer()
    {
        return this._corcheteDer_;
    }

    public void setCorcheteDer(TCorcheteDer node)
    {
        if(this._corcheteDer_ != null)
        {
            this._corcheteDer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corcheteDer_ = node;
    }

    public LinkedList<PElemento> getLetra()
    {
        return this._letra_;
    }

    public void setLetra(List<?> list)
    {
        for(PElemento e : this._letra_)
        {
            e.parent(null);
        }
        this._letra_.clear();

        for(Object obj_e : list)
        {
            PElemento e = (PElemento) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._letra_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._corcheteIzq_)
            + toString(this._m_)
            + toString(this._dosPuntos_)
            + toString(this._s_)
            + toString(this._pPunto_)
            + toString(this._c_)
            + toString(this._corcheteDer_)
            + toString(this._letra_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._corcheteIzq_ == child)
        {
            this._corcheteIzq_ = null;
            return;
        }

        if(this._m_ == child)
        {
            this._m_ = null;
            return;
        }

        if(this._dosPuntos_ == child)
        {
            this._dosPuntos_ = null;
            return;
        }

        if(this._s_ == child)
        {
            this._s_ = null;
            return;
        }

        if(this._pPunto_ == child)
        {
            this._pPunto_ = null;
            return;
        }

        if(this._c_ == child)
        {
            this._c_ = null;
            return;
        }

        if(this._corcheteDer_ == child)
        {
            this._corcheteDer_ = null;
            return;
        }

        if(this._letra_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._corcheteIzq_ == oldChild)
        {
            setCorcheteIzq((TCorcheteIzq) newChild);
            return;
        }

        if(this._m_ == oldChild)
        {
            setM((TNumero) newChild);
            return;
        }

        if(this._dosPuntos_ == oldChild)
        {
            setDosPuntos((TDosPuntos) newChild);
            return;
        }

        if(this._s_ == oldChild)
        {
            setS((TNumero) newChild);
            return;
        }

        if(this._pPunto_ == oldChild)
        {
            setPPunto((TPPunto) newChild);
            return;
        }

        if(this._c_ == oldChild)
        {
            setC((TNumero) newChild);
            return;
        }

        if(this._corcheteDer_ == oldChild)
        {
            setCorcheteDer((TCorcheteDer) newChild);
            return;
        }

        for(ListIterator<PElemento> i = this._letra_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PElemento) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
