/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.node;

import lyrics.analysis.*;

@SuppressWarnings("nls")
public final class Start extends Node
{
    private PCancion _pCancion_;
    private EOF _eof_;

    public Start()
    {
        // Empty body
    }

    public Start(
        @SuppressWarnings("hiding") PCancion _pCancion_,
        @SuppressWarnings("hiding") EOF _eof_)
    {
        setPCancion(_pCancion_);
        setEOF(_eof_);
    }

    @Override
    public Object clone()
    {
        return new Start(
            cloneNode(this._pCancion_),
            cloneNode(this._eof_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PCancion getPCancion()
    {
        return this._pCancion_;
    }

    public void setPCancion(PCancion node)
    {
        if(this._pCancion_ != null)
        {
            this._pCancion_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pCancion_ = node;
    }

    public EOF getEOF()
    {
        return this._eof_;
    }

    public void setEOF(EOF node)
    {
        if(this._eof_ != null)
        {
            this._eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eof_ = node;
    }

    @Override
    void removeChild(Node child)
    {
        if(this._pCancion_ == child)
        {
            this._pCancion_ = null;
            return;
        }

        if(this._eof_ == child)
        {
            this._eof_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(Node oldChild, Node newChild)
    {
        if(this._pCancion_ == oldChild)
        {
            setPCancion((PCancion) newChild);
            return;
        }

        if(this._eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    public String toString()
    {
        return "" +
            toString(this._pCancion_) +
            toString(this._eof_);
    }
}
