/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.node;

import lyrics.analysis.*;

@SuppressWarnings("nls")
public final class TMetadatoIgnorado extends Token
{
    public TMetadatoIgnorado(String text)
    {
        setText(text);
    }

    public TMetadatoIgnorado(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMetadatoIgnorado(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMetadatoIgnorado(this);
    }
}
