/* This file was generated by SableCC (http://www.sablecc.org/). */

package lyrics.node;

import lyrics.analysis.*;

@SuppressWarnings("nls")
public final class TPPunto extends Token
{
    public TPPunto()
    {
        super.setText(".");
    }

    public TPPunto(int line, int pos)
    {
        super.setText(".");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPPunto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPPunto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPPunto text.");
    }
}
